// <auto-generated />
using budget_tracker_backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace budget_tracker_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506183000_AddCategoryColor")]
    partial class AddCategoryColor
    {
    }
}
